browser:
  executable: "google-chrome-stable"
  url: "https://www.google.com"
  process_name: "chrome"


monitoring:
  check_frequency_seconds: 60

timeouts:
  blacklist_timeout_minutes: 10
  bathroom_break_minutes: 10
  bathroom_break_interval_hours: 3

backgrounds:
  normal: "~/.config/inappropriate-video-handler/wallpaper/normal.jpg"
  blocked: "~/.config/inappropriate-video-handler/wallpaper/blocked.jpg"
  bathroom_break: "~/.config/inappropriate-video-handler/wallpaper/bathroom.jpg"

files:
  blacklist: "~/.config/inappropriate-video-handler/BlackList.txt"
  whitelist: "~/.config/inappropriate-video-handler/WhiteList.txt"
  state_file: "/tmp/ivh_state.json"